bracketSpacing: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-solidity"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.17"
      tabWidth: 4
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
